stages:
  - stage: CI
    jobs:

    - job: TerraformCI
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - script: az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
        displayName: 'Azure Login'

      - script: cd modules/terraform-azurerm-vnet-peering && terraform init
        displayName: 'Terraform Init'

      - script: cd modules/terraform-azurerm-vnet-peering && terraform fmt
        displayName: 'Terraform Format'

      - script: cd modules/terraform-azurerm-vnet-peering && terraform validate
        displayName: 'Terraform Validate'
      
      - script: cd modules/terraform-azurerm-vnet-peering && terraform plan
        displayName: 'Terraform Plan'
